### PR TITLE
Improve project structure and build

### PR DESCRIPTION
**Pull request by gselzer**
Goals of this PR:
* [x] Refactor `scijava/` directory into `src/scyjava/` directory. See [this article](https://hynek.me/articles/testing-packaging/) for the benefits 
* [x] Remove `setup.py` in favor of `setup.cfg`. This seems to be the [preferred approach](https://docs.python.org/3/distutils/configfile.html) nowadays.
* [x] ~~Set up tox for stronger testing~~ *Let's just use pytest instead, as far as I can tell it's easier on Github Actions when using conda*
* [x] Devise a linting strategy (using black)
* [x] Devise a code coverage strategy
* [x] Allow these features to block merge through Github Actions

### CODE REVIEW

**Comment by gselzer** [comment]
Remaining questions:

* Do we continue to use the established Codecov technology or do we switch to another technology? I know that @ctrueden prefers the latter, but it would require a nontrivial amount of work.

**Review by ctrueden — COMMENTED** [review]
Here are the notes from our joint review:

* [ ] `tests` folder is not present in .tar.gz artifact.
* `Provides-Extra: test` appears in scyjava, but not cryptography.
* Both scyjava and cryptography have test deps in `requires.txt`, which is probably good?
* The cryptography project _does_ publish its tests folder, but our current packaging does not.
* [ ] `setup.cfg` has trailing whitespace. Git hates this.
* [ ] `author = Curtis Rueden, Philipp Hanslovsky, Edward Evans, Mark Hiner` should include Gabriel Selzer now.
* [ ] For `project_urls:`, napari also has:
    ```
    Documentation = https://napari.org
    Source Code = https://github.com/napari/napari
    ```
* [ ] In both the tar.gz and whl:
    ```
    -License: Public domain
    +License: UNKNOWN
    ```

**Comment by gselzer** [comment]
@ctrueden I cannot seem to find either `License` or `Provides-Extra` in either the repo or in the distribution. Where did we see that?

**Comment by gselzer** [comment]
> @ctrueden I cannot seem to find either `License` or `Provides-Extra` in either the repo or in the distribution. Where did we see that?

Aha, it's in the `PKG-INFO` of the distribution. Disregard :sweat_smile:

**Comment by ctrueden** [comment]
> I cannot seem to find either `License` or `Provides-Extra` in either the repo or in the distribution. Where did we see that?

Do I have the tool for you! https://github.com/BurntSushi/ripgrep 😁

**Comment by gselzer** [comment]
> * `Provides-Extra: test` appears in scyjava, but not cryptography.

Okay, so this guy *does* actually appear in cryptography. `Provides-Extra` is added to `PKG-INFO` in the distribution for *each* grouping in [`setup.cfg`](https://github.com/scijava/scyjava/blob/519b7cedb16fa89d4b1bf003d923d522c86a86a9/setup.cfg#L50)

If you download [the `cryptography` tarball](https://pypi.org/project/cryptography/#files) and `cat` the `PKG-INFO`, you'll see that it has one `Provides-Extra` entry for each of its [`options.extras_require`](https://github.com/pyca/cryptography/blob/03bb4b2c58a66649bb9d24504474a3b56dfd4928/setup.cfg#L58) groupings.

This `Provides-Extra` then allows you to to install the test dependencies as an [extra](https://peps.python.org/pep-0508/#extras)

In bash, you could write
```python3
python -m pip install scyjava[test]
```
(In zsh, you'd need quotes around `scyjava[test]`)

I don't think we should mess with this `Provides-Extra`s - it seems like a benefit, wouldn't you agree @ctrueden?

**Comment by ctrueden** [comment]
> I don't think we should mess with this `Provides-Extra`s - it seems like a benefit, wouldn't you agree @ctrueden?

Yep! Thanks for the explanation. Let's leave it as is.

**Comment by gselzer** [comment]
> > I cannot seem to find either `License` or `Provides-Extra` in either the repo or in the distribution. Where did we see that?
> 
> Do I have the tool for you! https://github.com/BurntSushi/ripgrep grin

Thanks for the suggestion!

**Comment by ctrueden** [comment]
> These spaces aren't in the repository's `setup.cfg`, but they _are_ in the distribution?

Ehh, not our problem then. :smile:

**Comment by gselzer** [comment]
@ctrueden all checkboxes should be solved now. Shall we merge?

**Comment by ctrueden** [comment]
Nice work, @gselzer!

**Pull request merged**
