### PR TITLE
Add JVM config shortcuts

### PR DESCRIPTION
**Pull request by ctrueden**
This patch series adds functions to scyjava.config making it easier to configure commonly desired adjustments to the JVM, including initial and maximum heap sizes, headless mode, and JDWP-based remote debugging. It also adds API for querying the JVM's memory state and available processors, as well as a shortcut to Java's `System.gc()` function. Finally, it adds tests for the memory and headless settings, as well as improving the integration tests in general.

### CODE REVIEW

**Comment by ctrueden** [comment]
@elevans I got a little carried away after we discussed these sorts of convenience functions this morning. :sweat_smile: I hope you like it!

**Comment by ctrueden** [comment]
Ahh, it looks like we would need to run inside `xvfb` to truly test the not-headless-by-default assumption. I'll add a workaround for now.

**Comment by ctrueden** [comment]
OK, this codecov check is annoying, so I'm going to quit working on this. I added integration tests exercising most of the functionality, but our codecov configuration does not appreciate it.

**Review by elevans — APPROVED** [review]
@ctrueden Great additions to `scyjava`! I tried out all the new methods without issue and your docstrings are clear and comprehensive. I especially appreciate the remote debugging!

**Pull request merged**
