### PR TITLE
Prevent error when JVM is already running.

### PR DESCRIPTION
**Pull request by hadim**
See https://github.com/imagej/pyimagej/issues/29 for details.

### CODE REVIEW

**Comment by hanslovsky** [comment]
I do not agree that this check should be the responsibility of `scyjava`. As a (fairly) low-level library that does not do any UI work itself, I think that `scyjava` should fail if used incorrectly. The exception holds valuable information about improper use, which might get lost if only a warning is emitted and the python logging system has not been initialized.

What is the reasoning for not checking for the `ValueError` exception down-stream? If that exception is too broad, we could create a new exception and re-throw.

**Comment by hadim** [comment]
I understand your point.

But running twice the same line without modifying anything else and get an error only the second time is definitively not the correct pattern in my opinion.

I know the scyjava/pyimage/jnius init mechanism is complex but we should be able to run (or the equivalent scyjava code):

```python
import imagej
imagej.init()
```

twice without running into an error.

Do you guys (@ctrueden and @hanslovsky) think this issue could be addressed elsewhere? Or do you think that issue should only be handled at the user level?

**Comment by hanslovsky** [comment]
> But running twice the same line without modifying anything else and get an error only the second time is definitively not the correct pattern in my opinion.

I agree but that is a general problem with (stateful) singletons: Running the same thing multiple times will produce different result depending on the global state.

> Do you guys hink this issue could be addressed elsewhere?

`imagej.init()` looks like a good candidate to me. The [`scyjava_config` portion](https://github.com/imagej/pyimagej/blob/05a1a501935beddfcb5b604f3ae7ede34b9e2a70/imagej/imagej.py#L74-L101) of the code could be run only if pyjnius is not initialized.

**Comment by hadim** [comment]
For the record: https://github.com/imagej/pyimagej/pull/30

**Comment by hanslovsky** [comment]
Thanks @hadim

**Pull request closed without merging**
